# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that deploys hello-app-runner app
Parameters:
  ServiceName:
    Type: String
    Description: Name for your App Runner service.
  ImageUri:
    Type: String
    Description: ImageUri
Resources:
  Service:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerDeployRole.Arn
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: !Ref ImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: 8080
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt InstanceRole.Arn
        Cpu: 1024
        Memory: 2048

  AppRunnerDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-AppRunnerDeployRole
      Description: Role for App Runner instance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AllowAccessToAppRunner
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apprunner:*
                Resource: '*'
        - PolicyName: AllowAccessToECR
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: '*'
        - PolicyName: AllowAccessToLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: '*'

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-InstanceRole
      Description: Role for App Runner instance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - tasks.apprunner.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AllowAccessToBedrock
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'


Outputs:
  Endpoint:
    Description: "The endpoint of the App Runner service."
    Value: !GetAtt Service.ServiceUrl